export interface producto{
    _id: string,
    id_categoria : {descripcion: string, imagen: string, nombre: string},
    nombre: string,
    descripcion: string,
    beneficios: string,
    caracteristicas: string,
    precio: string,
    stock: string,
    imagen: string,
    categoria: string,
    ingrediente: string,
    tipo: string,
    aroma: string,
}